version:  '3.7'

services:
  nginx:
    image: codebuds/nginx:prod-1.0.1
    restart: on-failure
    working_dir: /var/www/symfony
    volumes:
      - ./public:/var/www/symfony/public:cached
    networks:
      - web
      - internal
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackfiresdk.rule=Host(`blackfiresdk.localhost`)"
      - "traefik.http.routers.blackfiresdk.entrypoints=http"

  php:
    image: codebuds/php:dev-latest
    user: exploit
    restart: on-failure
    networks:
      - internal
      - maria
    external_links:
      - maria:maria
    environment:
      - DATABASE_URL=mysql://exploit:exploit@maria:3306/blackfiresdk
      - APP_ENV=dev
    volumes:
      - ./:/var/www/symfony:cached
    command: >
      sh -c "cd /var/www/symfony
      && composer install
      && composer dump-autoload --optimize
      && php bin/console doctrine:database:create -n --if-not-exists
      && php bin/console doctrine:migrations:migrate -n --allow-no-migration
      && php bin/console cache:warmup
      && php-fpm"

##  Blackfire agent
#  blackfire:
#    image: blackfire/blackfire
#    networks:
#      - internal
#    ports:
#      - 8707
#    environment:
#      - BLACKFIRE_SERVER_ID=~
#      - BLACKFIRE_SERVER_TOKEN=~
#      - BLACKFIRE_CLIENT_ID=~
#      - BLACKFIRE_CLIENT_TOKEN=~

##  Blackfire probe app
#  blackfire_probe:
#    image: codebuds/php:blackfire-1.0.2
#    restart: on-failure
#    networks:
#      - internal
#      - maria
#    external_links:
#      - maria:maria
#    environment:
#      - DATABASE_URL=mysql://user:pass@maria:3306/blackfiresdk
#      - APP_ENV=prod
#    volumes:
#      - ./:/var/www/symfony:cached
#    command: >
#      sh -c "cd /var/www/symfony
#      && composer install
#      && composer dump-autoload --optimize
#      && php bin/console doctrine:database:create -n --if-not-exists
#      && php bin/console doctrine:migrations:migrate -n --allow-no-migration
#      && php bin/console cache:warmup
#      && php-fpm"

networks:
  maria:
    external: true
  web:
    external: true
  internal:
